### ISSUE TITLE
Generator ignores additionalProperties: true

### ISSUE THREAD

**Issue by kotyara85** [google/gnostic-grpc#102]
Hey there,
I have this openapi spec component:
```
    Response:
      properties:
        uid:
          type: string
        data:
          type: object
          additionalProperties: true
```

oapi generator would translate data field into map[string]interface{}

gnostic-grpc can not produce ad working proto, here's the output after I converted to binary pb using gnostic:
```
message Data {
}
```

Thanks
